spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit_db
    username: postgres
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: never

